name: Update Workflow in Repos

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  update-workflow:
    runs-on: ubuntu-latest
    
    env:
      GH_TOKEN: ${{ github.token }}
      
    steps:
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq -y
          
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read updated workflow.yml content
        id: read-content
        run: |
          echo "::set-output name=content::$(cat gpg-signature-verification.yml)"
        working-directory: workflows

      - name: List Repositories in the GitHub organization
        id: list-repos
        run: |
          repos=$(gh repo list "Tejaswi-Test-Organization" --json 'name' --jq '.[] | .name' | paste -sd " ")
          echo "Repos: $repos"
          echo "::set-output name=repos::$repos"

      - name: Update GPG signature Verification Workflow in Repos
        id: update-repos
        run: |
          for repo in ${{ steps.list-repos.outputs.repos }}; do
            repo_name=$(echo $repo | cut -f 1)
            if [ "$repo_name" = "Signature-Verification-Workflow" ] || [ "$repo_name" = "GitHub-App" ]; then
              echo "Skipping repository: $repo_name"
              continue
            fi
            echo "Updating workflow.yml in repository: $repo_name"
            gh api repos/Tejaswi-Test-Organization/$repo_name/contents/.github/workflows/workflow.yml -F "message=Update workflow.yml" -F "content=$(echo '${{ steps.read-content.outputs.content }}' | base64)" --method PUT
          done
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
